### ISSUE TITLE
add_criterion method returning errors

### ISSUE THREAD

**Issue by sbrosnihan** [sheagcraig/python-jss#34] opened 2015-04-16 21:55 UTC
Thanks for all the hard work on this. It sure makes interacting with the JSS API easier! I have a problem that may be related to improper usage by me or a bug.  I've created a variable: 

    jss_prefs = jss.JSSPrefs()
    j = jss.JSS(jss_prefs, ssl_verify=False, suppress_warnings=True)
    smartGroup = j.ComputerGroup(99)

When trying to add criteria to smartGroup (which is a smart group), I get the following error:

    smartGroup.add_criterion(name="Username", priority=0, and_or="and", search_type="is", value="bobafett2")
    self.criteria.append(criterion)
    AttributeError: 'ComputerGroup' object has no attribute 'criteria'

I can see the contents of the group and criteria, also inspect.getargspec(smartGroup.add_criterion)
returns this:

    ArgSpec(args=['self', 'name', 'priority', 'and_or', 'search_type', 'value'], varargs=None, keywords=None, defaults=None)

**Comment by sheagcraig** [comment] 2015-04-17 13:07
Thanks!

Looking over the code, I can see what the issue is, and it's *not you*!

Python raises AttributeError, rightly so, because indeed the ComputerGroup has no attribute 'criteria'. This attribute is set in the new() method, but not for a ComputerGroup that you pull from the server.

I'll have to fix that!

In the meantime, if you add the attribute as a list, you'll be good to go.
e.g.
```
jss_prefs = jss.JSSPrefs()
j = jss.JSS(jss_prefs, ssl_verify=False, suppress_warnings=True)
smartGroup = j.ComputerGroup(99)
# Here's the only change...
smartGroup.criteria = []
smartGroup.add_criterion(name="Username", priority=0, and_or="and", search_type="is", value="bobafett2")
```

**Comment by sheagcraig** [comment] 2015-04-17 13:28
I'm sorry, that's actually wrong.

```criteria``` is not a list, it's an xml.etree.Element.

You should be able to do this to "find" it and assign it to ```ComputerGroup.criteria```, and then append should work.

```
ss_prefs = jss.JSSPrefs()
j = jss.JSS(jss_prefs, ssl_verify=False, suppress_warnings=True)
smartGroup = j.ComputerGroup(99)
# Here's the only change... Finds the criteria element that comes 
# with the XML and assigns it to a convenient attribute.
smartGroup.criteria = smartGroup.find("criteria")
smartGroup.add_criterion(name="Username", priority=0, and_or="and", search_type="is", value="bobafett2")
```

**Comment by sbrosnihan** [comment] 2015-04-17 17:00
Bingo! Works like a charm.

**Comment by sheagcraig** [comment] 2015-04-21 13:39
I'm going to keep this open so I remember to fix it!

**Comment by sbrosnihan** [comment] 2015-05-01 12:15
It would be great if there were a remove_criterion method in the JSSGroupObject class. Maybe it would just need to receive a value? We're manipulating a smart group extensively by adding and removing criteria by the hundreds. We make incremental changes, so just purging the entire group won't fly. I may fork and poke at things...so little time...and again, thanks for python-jss!

**Comment by sheagcraig** [comment] 2015-05-20 19:30
@sbrosnihan I just added in the code to (at least) handle your first question about this issue. It's in testing now-should get released in the next 24 hours to production/master.

As for the issue about "or" getting switched to "and", I just tried it on jss v9.6 and it successfully lets me set "or" for the "and_or" part of a criterion.

Just playing around, I did see that I could add a criterion with wacky values and it just smoothes them over. For example:
```
g.add_criterion(name="Username", priority=1, and_or="tacos", search_type="is", value="bobafett2")
g.save()
```
results in a smart group with the above criteria's and_or value set to "and", despite _clearly_ being asked to set it to tacos.

I'm sure this is a dumb question, but are you sure you're setting the and_or to the string value "or"? The python_jss end of it does zero validation, so it will happily let you assign any value to and_or, and it appears that the JSS will happily accept anything, and just turn it into "and".

Why this would then "and" all of your other criteria, I'm not sure!

If this is still an issue for you, let's open another issue to handle it, since the initial one here is now solved.

Thanks!

**Closed by sheagcraig** 2015-05-20 19:30 UTC
